[package]
name = "sha256_calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha256 = "1.0.3"
rand = "0.8.4"
core_affinity = "0.5.10"
crossbeam = "0.8.1"
